site_name: RULE OF FEAR
site_url: https://c7d5a6.github.io/rule-of-fear
site_description: Rule of Fear Wiki
site_author: c7d5a6
repo_url: https://github.com/c7d5a6/rule-of-fear/
pages:
- Home: index.md
- Diary: diary.md
- NPC: 
  - Ravengro:      npc/npc_ravengro.md
  - Tamrivena:     npc/npc_tamrivena.md
  - Kurtu:         npc/npc_kurtu.md
  - Lepidstadt:    npc/npc_lepid.md
  - Wispering Way: npc/npc_ww.md
  - Other:         npc/npc_other.md
- Places: places.md
- PC: pc.md
- About: about.md
theme: readthedocs
extra_css: 
  - extra.css
plugins:
  - search
