site_name: RULE OF FEAR
site_url: https://c7d5a6.github.io/rule-of-fear
site_description: Rule of Fear Wiki
site_author: c7d5a6
repo_url: https://github.com/c7d5a6/rule-of-fear/
google_analytics: ['UA-110463421-1', 'auto']
pages:
- Home: index.md
- Дневник: diary.md
- NPC:
  - Равенгро:      npc/npc_ravengro.md
  - Тамривена:     npc/npc_tamrivena.md
  - Курту:         npc/npc_kurtu.md
  - Лепидштадт:    npc/npc_lepid.md
  - Шепчущий Путь: npc/npc_ww.md
  - Другие:        npc/npc_other.md
- Места: places.md
- Вещи: items.md
- PC: pc.md
- Записи:
  - Песенка из Равенгро: notes/song_ravengro.md
  - Завещание: notes/will.md
  - Журнал: notes/journal.md
  - Письма: notes/letters.md
  - Книги: notes/history-book.md
- Правила:
  - Horror Adventures: rules/horror_adventures.md
- Классы:
  - Forsworn Paladin: classes/forsworn_paladin.md
theme: readthedocs
extra_javascript:
  - search/lunr.multi.js
  - search/lunr.ru.js
  - search/lunr.stemmer.support.js
  - search/search.js
extra_css:
  - css/extra.css
plugins:
  - search
